### ISSUE TITLE
Intersection observer API as reusable helper

### ISSUE THREAD

**Issue by tomvaillant** [the-pudding/sleep-training#2]
How could I set up a helper that uses the intersection observer API to calculate when the component from which it is called is in viewport, returning true to then toggle animations.

**Comment by matthewfdaniels** [comment]
could you give an example of this? i think your code is setup to this already.

**Comment by tomvaillant** [comment]
Of course! 

1) I'd like the video in the Video.svelte component to start autoplaying once it is visible in viewport (not once the component is mounted)
2) Similarly I'd like to start the fly in animation of the Mosaic component images once it is in viewport.

Thanks :)

**Comment by matthewfdaniels** [comment]
it might depend on where that component is. this variable `active` will turn true when the step is in view

<img width="517" alt="image" src="https://github.com/tomvaillant/sleep-training/assets/2880174/fbf5c841-2cda-4497-a608-15607658dc10">

but if you're working on the sticky component, you'll have to use the `step` variable and wait until it turns a certain value. once it does, you'll trigger something in the video component (to either create it or start from zero or play it)...same thing with mosaic...waiting for the step and then triggering a behavior.

flyfade animations require a bit of nuance because they only trigger when the element is created/removed. you can get around this by using the {#key}
https://learn.svelte.dev/tutorial/key-blocks

happy to pair code with you on this!
