### ISSUE TITLE
Disable re-rendering of force simulation if renderedData values do not change

### ISSUE THREAD

**Issue by tomvaillant** [the-pudding/sleep-training#3]
I'm currently running the step logic in Index.svelte, calling a specific function containing this logic as a prop in the corresponding Section component lower down.

I'd like to avoid the force simulation re-rendering and re-positioning circles if the renderedData values do not change.

**Comment by matthewfdaniels** [comment]
the reason why it's re-rendering is because this statement will re-run every time a variable within it changes

<img width="410" alt="image" src="https://github.com/tomvaillant/sleep-training/assets/2880174/b12ec999-fa5d-48c3-9037-d9526fd65f53">

So since `step` is changing, it's re-running stepHandler and generating a new array for `newValues` that's identical to the one before it.

we can probably debug this later, but my gut is that you pre-render/calculate everything at the start and then store those positions somewhere, passing them to the components as neccessary.

**Comment by tomvaillant** [comment]
This sounds like a larger structural change, happy to wait until later to look into it!
