### ISSUE TITLE
Make the tooltip clickable

### ISSUE THREAD

**Issue by tomvaillant** [the-pudding/sleep-training#4]
The button in the Tooltip component is currently not clickable, I'm not sure how to fix that.

**Comment by matthewfdaniels** [comment]
you can make the tooltip clickable by add this to the css

<img width="536" alt="image" src="https://github.com/tomvaillant/sleep-training/assets/2880174/3bfc6515-cc15-4a09-bba7-472ef0b81337">

but the problem is that you can't access the tooltip because it fades away when you try to click it. i removed the mouseout event and it's then clickable (after you turn on pointer events)

<img width="697" alt="image" src="https://github.com/tomvaillant/sleep-training/assets/2880174/2da8b005-637b-4191-8ac2-ac6d6e60781f">

but this opens up more weird UX things, where you you need to get to the tooltip to click it, but you also need it to go away when you want it to. I think I would consider the role you want the tooltips to play and how people should interact with them.

**Comment by tomvaillant** [comment]
Thanks Matt that's a good point, maybe no need to have a redirect to the source since the data will be publicly accessible.
