### ISSUE TITLE
Timeline component pre-rendering

### ISSUE THREAD

**Issue by tomvaillant** [the-pudding/sleep-training#7]
For some reason the Timeline component, used on line 222 in Index.svelte (loaded in the Section.svelte component) is flickering before it scrolls into viewport. I've set it up the same as Bubbles and Map which don't have this issue.

**Comment by matthewfdaniels** [comment]
add `$: console.log(step)` to `Section` and you'll see why it's flickering. the browser sees step constantly changing between undefined and 0. Since `Timeline` requires a step of `0` it's appearing and disappearing as `step` goes back and forth. 

`step` is undefined until you enter the sticky section, and once you enter the sticky section, it starts at 0

easiest fix here is to add this, which will render the timeline, even when step is undefined (`!step`)
<img width="572" alt="image" src="https://github.com/tomvaillant/sleep-training/assets/2880174/0704e9d0-d162-4ce9-a0b6-428af47a4302">

**Comment by tomvaillant** [comment]
Solved! Thank you :)
